# Generated by Django 5.2.6 on 2025-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_information_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
