# Generated by Django 5.2.5 on 2025-09-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_app', '0002_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('expirs', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
