# Generated by Django 5.2.6 on 2025-09-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount_app', '0003_otp_alter_user_fullname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='username',
        ),
    ]
