# Generated by Django 5.2.6 on 2025-10-01 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='code',
            new_name='discount',
        ),
    ]
